version: '3.9'

services:
  app:
    build: .
    container_name: cocos-api
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - cocosnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: cocos-pgadmin
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@cocos.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-config/servers.json:/pgadmin4/servers.json
    depends_on:
      - postgres
    networks:
      - cocosnet

  postgres:
    image: postgres:15
    container_name: cocos-db
    restart: always
    environment:
      POSTGRES_DB: cocos
      POSTGRES_USER: cocos_user
      POSTGRES_PASSWORD: cocos_pass
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./database.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '5432:5432'
    networks:
      - cocosnet

volumes:
  db_data:

networks:
  cocosnet:
